# Generated by Django 5.0.3 on 2024-06-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('classes_number', models.IntegerField()),
            ],
        ),
    ]
