# Generated by Django 5.0.3 on 2024-06-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='classes_number',
            new_name='number_of_classes',
        ),
    ]
