# Generated by Django 5.0.3 on 2024-06-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_classes_number_teacher_number_of_classes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('full_name', 'date_of_birth')},
        ),
    ]
